apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-user/nginx-ingress-demo-gitops.git'
    targetRevision: HEAD
    path: charts/my-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
